// Generated by gencpp from file loc_msgs/GeometryMsgsVector3.msg
// DO NOT EDIT!


#ifndef LOC_MSGS_MESSAGE_GEOMETRYMSGSVECTOR3_H
#define LOC_MSGS_MESSAGE_GEOMETRYMSGSVECTOR3_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace loc_msgs
{
template <class ContainerAllocator>
struct GeometryMsgsVector3_
{
  typedef GeometryMsgsVector3_<ContainerAllocator> Type;

  GeometryMsgsVector3_()
    : x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  GeometryMsgsVector3_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;




  typedef boost::shared_ptr< ::loc_msgs::GeometryMsgsVector3_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::loc_msgs::GeometryMsgsVector3_<ContainerAllocator> const> ConstPtr;

}; // struct GeometryMsgsVector3_

typedef ::loc_msgs::GeometryMsgsVector3_<std::allocator<void> > GeometryMsgsVector3;

typedef boost::shared_ptr< ::loc_msgs::GeometryMsgsVector3 > GeometryMsgsVector3Ptr;
typedef boost::shared_ptr< ::loc_msgs::GeometryMsgsVector3 const> GeometryMsgsVector3ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::loc_msgs::GeometryMsgsVector3_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::loc_msgs::GeometryMsgsVector3_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace loc_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'loc_msgs': ['/proj/catkinws/src/loc_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::loc_msgs::GeometryMsgsVector3_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::loc_msgs::GeometryMsgsVector3_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::loc_msgs::GeometryMsgsVector3_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::loc_msgs::GeometryMsgsVector3_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::loc_msgs::GeometryMsgsVector3_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::loc_msgs::GeometryMsgsVector3_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::loc_msgs::GeometryMsgsVector3_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4a842b65f413084dc2b10fb484ea7f17";
  }

  static const char* value(const ::loc_msgs::GeometryMsgsVector3_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4a842b65f413084dULL;
  static const uint64_t static_value2 = 0xc2b10fb484ea7f17ULL;
};

template<class ContainerAllocator>
struct DataType< ::loc_msgs::GeometryMsgsVector3_<ContainerAllocator> >
{
  static const char* value()
  {
    return "loc_msgs/GeometryMsgsVector3";
  }

  static const char* value(const ::loc_msgs::GeometryMsgsVector3_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::loc_msgs::GeometryMsgsVector3_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::loc_msgs::GeometryMsgsVector3_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::loc_msgs::GeometryMsgsVector3_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GeometryMsgsVector3_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::loc_msgs::GeometryMsgsVector3_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::loc_msgs::GeometryMsgsVector3_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOC_MSGS_MESSAGE_GEOMETRYMSGSVECTOR3_H
