// Generated by gencpp from file loc_msgs/GeometryMsgsPoseWithEulerAngles.msg
// DO NOT EDIT!


#ifndef LOC_MSGS_MESSAGE_GEOMETRYMSGSPOSEWITHEULERANGLES_H
#define LOC_MSGS_MESSAGE_GEOMETRYMSGSPOSEWITHEULERANGLES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <loc_msgs/GeometryMsgsVector3.h>
#include <loc_msgs/GeometryMsgsEulerAngles.h>

namespace loc_msgs
{
template <class ContainerAllocator>
struct GeometryMsgsPoseWithEulerAngles_
{
  typedef GeometryMsgsPoseWithEulerAngles_<ContainerAllocator> Type;

  GeometryMsgsPoseWithEulerAngles_()
    : position()
    , attitude()  {
    }
  GeometryMsgsPoseWithEulerAngles_(const ContainerAllocator& _alloc)
    : position(_alloc)
    , attitude(_alloc)  {
  (void)_alloc;
    }



   typedef  ::loc_msgs::GeometryMsgsVector3_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef  ::loc_msgs::GeometryMsgsEulerAngles_<ContainerAllocator>  _attitude_type;
  _attitude_type attitude;




  typedef boost::shared_ptr< ::loc_msgs::GeometryMsgsPoseWithEulerAngles_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::loc_msgs::GeometryMsgsPoseWithEulerAngles_<ContainerAllocator> const> ConstPtr;

}; // struct GeometryMsgsPoseWithEulerAngles_

typedef ::loc_msgs::GeometryMsgsPoseWithEulerAngles_<std::allocator<void> > GeometryMsgsPoseWithEulerAngles;

typedef boost::shared_ptr< ::loc_msgs::GeometryMsgsPoseWithEulerAngles > GeometryMsgsPoseWithEulerAnglesPtr;
typedef boost::shared_ptr< ::loc_msgs::GeometryMsgsPoseWithEulerAngles const> GeometryMsgsPoseWithEulerAnglesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::loc_msgs::GeometryMsgsPoseWithEulerAngles_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::loc_msgs::GeometryMsgsPoseWithEulerAngles_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace loc_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'loc_msgs': ['/proj/catkinws/src/loc_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::loc_msgs::GeometryMsgsPoseWithEulerAngles_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::loc_msgs::GeometryMsgsPoseWithEulerAngles_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::loc_msgs::GeometryMsgsPoseWithEulerAngles_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::loc_msgs::GeometryMsgsPoseWithEulerAngles_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::loc_msgs::GeometryMsgsPoseWithEulerAngles_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::loc_msgs::GeometryMsgsPoseWithEulerAngles_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::loc_msgs::GeometryMsgsPoseWithEulerAngles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bf8f92fdd630432242cec5aadb32d5d6";
  }

  static const char* value(const ::loc_msgs::GeometryMsgsPoseWithEulerAngles_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbf8f92fdd6304322ULL;
  static const uint64_t static_value2 = 0x42cec5aadb32d5d6ULL;
};

template<class ContainerAllocator>
struct DataType< ::loc_msgs::GeometryMsgsPoseWithEulerAngles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "loc_msgs/GeometryMsgsPoseWithEulerAngles";
  }

  static const char* value(const ::loc_msgs::GeometryMsgsPoseWithEulerAngles_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::loc_msgs::GeometryMsgsPoseWithEulerAngles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "GeometryMsgsVector3 position\n\
GeometryMsgsEulerAngles attitude\n\
\n\
================================================================================\n\
MSG: loc_msgs/GeometryMsgsVector3\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: loc_msgs/GeometryMsgsEulerAngles\n\
float64 roll\n\
float64 pitch\n\
float64 yaw\n\
";
  }

  static const char* value(const ::loc_msgs::GeometryMsgsPoseWithEulerAngles_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::loc_msgs::GeometryMsgsPoseWithEulerAngles_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.attitude);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GeometryMsgsPoseWithEulerAngles_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::loc_msgs::GeometryMsgsPoseWithEulerAngles_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::loc_msgs::GeometryMsgsPoseWithEulerAngles_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    s << std::endl;
    Printer< ::loc_msgs::GeometryMsgsVector3_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "attitude: ";
    s << std::endl;
    Printer< ::loc_msgs::GeometryMsgsEulerAngles_<ContainerAllocator> >::stream(s, indent + "  ", v.attitude);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOC_MSGS_MESSAGE_GEOMETRYMSGSPOSEWITHEULERANGLES_H
