// Generated by gencpp from file loc_msgs/GeometryMsgsPoseWithEulerAnglesStamped.msg
// DO NOT EDIT!


#ifndef LOC_MSGS_MESSAGE_GEOMETRYMSGSPOSEWITHEULERANGLESSTAMPED_H
#define LOC_MSGS_MESSAGE_GEOMETRYMSGSPOSEWITHEULERANGLESSTAMPED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <loc_msgs/GeometryMsgsPoseWithEulerAngles.h>

namespace loc_msgs
{
template <class ContainerAllocator>
struct GeometryMsgsPoseWithEulerAnglesStamped_
{
  typedef GeometryMsgsPoseWithEulerAnglesStamped_<ContainerAllocator> Type;

  GeometryMsgsPoseWithEulerAnglesStamped_()
    : header()
    , pose()  {
    }
  GeometryMsgsPoseWithEulerAnglesStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::loc_msgs::GeometryMsgsPoseWithEulerAngles_<ContainerAllocator>  _pose_type;
  _pose_type pose;




  typedef boost::shared_ptr< ::loc_msgs::GeometryMsgsPoseWithEulerAnglesStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::loc_msgs::GeometryMsgsPoseWithEulerAnglesStamped_<ContainerAllocator> const> ConstPtr;

}; // struct GeometryMsgsPoseWithEulerAnglesStamped_

typedef ::loc_msgs::GeometryMsgsPoseWithEulerAnglesStamped_<std::allocator<void> > GeometryMsgsPoseWithEulerAnglesStamped;

typedef boost::shared_ptr< ::loc_msgs::GeometryMsgsPoseWithEulerAnglesStamped > GeometryMsgsPoseWithEulerAnglesStampedPtr;
typedef boost::shared_ptr< ::loc_msgs::GeometryMsgsPoseWithEulerAnglesStamped const> GeometryMsgsPoseWithEulerAnglesStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::loc_msgs::GeometryMsgsPoseWithEulerAnglesStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::loc_msgs::GeometryMsgsPoseWithEulerAnglesStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace loc_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'loc_msgs': ['/proj/catkinws/src/loc_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::loc_msgs::GeometryMsgsPoseWithEulerAnglesStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::loc_msgs::GeometryMsgsPoseWithEulerAnglesStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::loc_msgs::GeometryMsgsPoseWithEulerAnglesStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::loc_msgs::GeometryMsgsPoseWithEulerAnglesStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::loc_msgs::GeometryMsgsPoseWithEulerAnglesStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::loc_msgs::GeometryMsgsPoseWithEulerAnglesStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::loc_msgs::GeometryMsgsPoseWithEulerAnglesStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8453e4e1bedb83c5348ac1d3dd06365a";
  }

  static const char* value(const ::loc_msgs::GeometryMsgsPoseWithEulerAnglesStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8453e4e1bedb83c5ULL;
  static const uint64_t static_value2 = 0x348ac1d3dd06365aULL;
};

template<class ContainerAllocator>
struct DataType< ::loc_msgs::GeometryMsgsPoseWithEulerAnglesStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "loc_msgs/GeometryMsgsPoseWithEulerAnglesStamped";
  }

  static const char* value(const ::loc_msgs::GeometryMsgsPoseWithEulerAnglesStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::loc_msgs::GeometryMsgsPoseWithEulerAnglesStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
GeometryMsgsPoseWithEulerAngles pose\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: loc_msgs/GeometryMsgsPoseWithEulerAngles\n\
GeometryMsgsVector3 position\n\
GeometryMsgsEulerAngles attitude\n\
\n\
================================================================================\n\
MSG: loc_msgs/GeometryMsgsVector3\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: loc_msgs/GeometryMsgsEulerAngles\n\
float64 roll\n\
float64 pitch\n\
float64 yaw\n\
";
  }

  static const char* value(const ::loc_msgs::GeometryMsgsPoseWithEulerAnglesStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::loc_msgs::GeometryMsgsPoseWithEulerAnglesStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GeometryMsgsPoseWithEulerAnglesStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::loc_msgs::GeometryMsgsPoseWithEulerAnglesStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::loc_msgs::GeometryMsgsPoseWithEulerAnglesStamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::loc_msgs::GeometryMsgsPoseWithEulerAngles_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOC_MSGS_MESSAGE_GEOMETRYMSGSPOSEWITHEULERANGLESSTAMPED_H
