// Generated by gencpp from file loc_msgs/GeometryMsgsVehicleMeasure.msg
// DO NOT EDIT!


#ifndef LOC_MSGS_MESSAGE_GEOMETRYMSGSVEHICLEMEASURE_H
#define LOC_MSGS_MESSAGE_GEOMETRYMSGSVEHICLEMEASURE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace loc_msgs
{
template <class ContainerAllocator>
struct GeometryMsgsVehicleMeasure_
{
  typedef GeometryMsgsVehicleMeasure_<ContainerAllocator> Type;

  GeometryMsgsVehicleMeasure_()
    : header()
    , speed(0.0)
    , steering(0.0)
    , yaw_rate(0.0)  {
    }
  GeometryMsgsVehicleMeasure_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , speed(0.0)
    , steering(0.0)
    , yaw_rate(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _speed_type;
  _speed_type speed;

   typedef double _steering_type;
  _steering_type steering;

   typedef double _yaw_rate_type;
  _yaw_rate_type yaw_rate;




  typedef boost::shared_ptr< ::loc_msgs::GeometryMsgsVehicleMeasure_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::loc_msgs::GeometryMsgsVehicleMeasure_<ContainerAllocator> const> ConstPtr;

}; // struct GeometryMsgsVehicleMeasure_

typedef ::loc_msgs::GeometryMsgsVehicleMeasure_<std::allocator<void> > GeometryMsgsVehicleMeasure;

typedef boost::shared_ptr< ::loc_msgs::GeometryMsgsVehicleMeasure > GeometryMsgsVehicleMeasurePtr;
typedef boost::shared_ptr< ::loc_msgs::GeometryMsgsVehicleMeasure const> GeometryMsgsVehicleMeasureConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::loc_msgs::GeometryMsgsVehicleMeasure_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::loc_msgs::GeometryMsgsVehicleMeasure_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace loc_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'loc_msgs': ['/proj/catkinws/src/loc_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::loc_msgs::GeometryMsgsVehicleMeasure_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::loc_msgs::GeometryMsgsVehicleMeasure_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::loc_msgs::GeometryMsgsVehicleMeasure_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::loc_msgs::GeometryMsgsVehicleMeasure_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::loc_msgs::GeometryMsgsVehicleMeasure_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::loc_msgs::GeometryMsgsVehicleMeasure_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::loc_msgs::GeometryMsgsVehicleMeasure_<ContainerAllocator> >
{
  static const char* value()
  {
    return "083a4d6765ac12611ad089409dc288d5";
  }

  static const char* value(const ::loc_msgs::GeometryMsgsVehicleMeasure_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x083a4d6765ac1261ULL;
  static const uint64_t static_value2 = 0x1ad089409dc288d5ULL;
};

template<class ContainerAllocator>
struct DataType< ::loc_msgs::GeometryMsgsVehicleMeasure_<ContainerAllocator> >
{
  static const char* value()
  {
    return "loc_msgs/GeometryMsgsVehicleMeasure";
  }

  static const char* value(const ::loc_msgs::GeometryMsgsVehicleMeasure_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::loc_msgs::GeometryMsgsVehicleMeasure_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float64 speed\n\
float64 steering\n\
float64 yaw_rate\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::loc_msgs::GeometryMsgsVehicleMeasure_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::loc_msgs::GeometryMsgsVehicleMeasure_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.speed);
      stream.next(m.steering);
      stream.next(m.yaw_rate);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GeometryMsgsVehicleMeasure_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::loc_msgs::GeometryMsgsVehicleMeasure_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::loc_msgs::GeometryMsgsVehicleMeasure_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "speed: ";
    Printer<double>::stream(s, indent + "  ", v.speed);
    s << indent << "steering: ";
    Printer<double>::stream(s, indent + "  ", v.steering);
    s << indent << "yaw_rate: ";
    Printer<double>::stream(s, indent + "  ", v.yaw_rate);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOC_MSGS_MESSAGE_GEOMETRYMSGSVEHICLEMEASURE_H
